# Generated by Django 5.2.4 on 2025-07-12 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(blank=True, related_name='project_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
