# Generated by Django 5.2.4 on 2025-07-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfig',
            name='webhook_url',
            field=models.URLField(max_length=500),
        ),
    ]
