# Generated by Django 5.2.4 on 2025-07-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_current_streak_user_longest_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_id',
        ),
    ]
