# Generated by Django 5.2.4 on 2025-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio_user_last_activity_date_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp_points',
            field=models.IntegerField(default=0),
        ),
    ]
